<a href="https://colab.research.google.com/github/sajedehfarahbod/training-deep-learning-with-PyTorch/blob/main/pytorch0ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot  as plt
print(torch.__version__)

2.2.1+cu121


#*scalar*

In [ ]:
scalar=torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
vector=torch.tensor([7,7])
vector
vector.ndim

1

In [ ]:
vector.shape


torch.Size([2])

In [ ]:
matrix=torch.tensor([[7 ,8] , [9,7]])
matrix.ndim
matrix.shape

torch.Size([2, 2])

In [ ]:
Torch= torch.tensor([[[1,2,3],[2,4,5],[4,5,6]]])
Torch.shape


torch.Size([1, 3, 3])

#Random tensors
https://pytorch.org/docs/stable/rand.html

In [ ]:
random_tensors= torch.rand(3,4)
random_tensors

tensor([[0.7758, 0.2215, 0.7596, 0.3357],
        [0.4498, 0.0216, 0.7223, 0.5071],
        [0.0509, 0.8389, 0.9850, 0.7872]])

In [ ]:
random_image_size_tensors= torch.rand(244,244,3) #height,width, colour channels(R,G,B)
random_image_size_tensors.shape , random_image_size_tensors.ndim

(torch.Size([244, 244, 3]), 3)

In [ ]:
torch.rand(size=(3,3))

tensor([[0.9934, 0.0304, 0.7205],
        [0.5172, 0.3298, 0.3742],
        [0.8376, 0.0854, 0.0516]])

#zero and ones

In [ ]:
zeros=torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*random_tensors

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones=torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

#range of tensors

In [ ]:
torch.arange(start=3,end=14,step=2)
one_ten=torch.arange(1,11)
one_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
ten_zeros = torch.zeros_like(input = one_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#tensors dtype

In [ ]:
float1=torch.tensor([3.0,5.9,6.0],dtype=None, device=None  , requires_grad=False)    #devoce="cuda"
float1


tensor([3.0000, 5.9000, 6.0000])

In [ ]:
float2=float1.type(torch.float16)
float2

tensor([3.0000, 5.8984, 6.0000], dtype=torch.float16)

In [ ]:
float1*float2

tensor([ 9.0000, 34.8008, 36.0000])

In [ ]:
int32=torch.tensor([3,6,9],dtype=torch.int32)
float1*int32

tensor([ 9.0000, 35.4000, 54.0000])

#getting information from tensor
tensors not right dtype(tensor.dtype)
tensors not right shape(tensor.shape)
tensors not right device(tensor.device)

In [ ]:
stensor=torch.rand(3,4)
stensor

tensor([[0.0666, 0.7718, 0.0142, 0.5933],
        [0.1140, 0.4378, 0.1317, 0.4676],
        [0.0444, 0.7993, 0.3871, 0.3100]])

In [ ]:
print(stensor)
print(f"{stensor.dtype}")
print(f"{stensor.shape}")
print(f"{stensor.size()}")
print(f"{stensor.device}")

tensor([[0.0666, 0.7718, 0.0142, 0.5933],
        [0.1140, 0.4378, 0.1317, 0.4676],
        [0.0444, 0.7993, 0.3871, 0.3100]])
torch.float32
torch.Size([3, 4])
torch.Size([3, 4])
cpu


In [ ]:
tensor=torch.tensor([1,4,6])
valu=0
for i  in range(len(tensor)):
    valu += tensor[i]*tensor[i]

print(valu)


tensor(53)


In [ ]:
tensor.matmul(tensor)

tensor(53)

In [ ]:
tensor_a=torch.tensor([[3,5],
                      [4,6],
                      [7,8]])
tensor_b=torch.tensor([[3,5],
                      [7,6],
                      [1,8]])
tensor_b.shape , tensor_a.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [ ]:
tensor_b.T.shape

torch.Size([2, 3])

In [ ]:


torch.matmul(tensor_a, tensor_b.T)

tensor([[34, 51, 43],
        [42, 64, 52],
        [61, 97, 71]])

In [ ]:
torch.matmul(tensor_a, tensor_b.T).shape

torch.Size([3, 3])

In [ ]:
x=torch.arange(0,100,10)
x , x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [ ]:
torch.min(x),torch.max(x) ,x.min()  , torch.mean(x.type(torch.float32)) , x.type(torch.float32).mean()

(tensor(0), tensor(90), tensor(0), tensor(45.), tensor(45.))

In [ ]:
#find the position of them
x.argmin() , x.argmax()

(tensor(0), tensor(9))

In [ ]:
# Create a tensor
import torch
x = torch.arange(1., 11.)
x, x.shape


(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(1, 10)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [ ]:
# Change view (keeps same data as original but changes view)
# See more: https://stackoverflow.com/a/54507446/7900723
z = x.view(1, 10)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [ ]:
# Changing z changes x
z[:, 0] = 5
z, x

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1) # try changing dim to dim=1 and see what happens
x_stacked

tensor([[ 5.,  5.,  5.,  5.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.]])

In [ ]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [ ]:
x_original.permute(0, 2, 1)[0, :,0].shape

torch.Size([3])

In [ ]:
# NumPy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
torch.from_numpy(array).type(torch.float32)

tensor([1., 2., 3., 4., 5., 6., 7.])

In [ ]:
import torch
import random

# # Set the random seed
RANDOM_SEED=50 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED)  #it is just for one line after it
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called
# Without this, tensor_D would be different to tensor_C
torch.random.manual_seed(seed=RANDOM_SEED)# try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.6180, 0.0687, 0.3893, 0.0404],
        [0.4013, 0.1442, 0.4605, 0.4877],
        [0.5927, 0.9634, 0.1230, 0.4048]])

Tensor D:
tensor([[0.6180, 0.0687, 0.3893, 0.0404],
        [0.4013, 0.1442, 0.4605, 0.4877],
        [0.5927, 0.9634, 0.1230, 0.4048]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

import torch
torch.manual_seed(0)
import random
random.seed(0)
import numpy as np
np.random.seed(0)

In [ ]:
!nvidia-smi

Sun Mar 17 17:27:04 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   47C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
# Check for GPU
import torch
torch.cuda.is_available()

True

In [ ]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'